language: go

go:
  - 1.9.2

bfore_install:
  - go get ./...
  - go get github.com/mattn/goveralls

script:
  - PATH="$HOME/gopath/bin:$PATH"
  - touch ${HOME}/coverage.out
  - go test -covermode=count -coverprofile=${HOME}/coverage.out
  - cat ${HOME}/coverage.out
  - ${GOPATH}/bin/goveralls -coverprofile=${HOME}/coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
