language: go

go:
  - 1.9.2

before_install:
  - go get ./...
  - go get github.com/mattn/goveralls

script:
  - go test ./...
  - ${GOPATH}/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
